### PR TITLE
Fix misc issues

### LINKED ISSUE #10: TypeInfo could have templated constructor

### LINKED ISSUE #11: TypeRegistry::registerType could get defaultValue by value instead of pointer

### PR DESCRIPTION
**Pull request by prybicki**
This PR is not well suited for full review. The most important parts (worth review) are marked with * in the list below.

- Redesigned Memory allocation structs (MemoryOwner, MemoryView) (*)
- Redesigned/added methods of ResourceManager: allocMemory(), copyMemory(), copyMemoryExternal() freeMemory() (*)
- Rewriten DataArray and improved interface (append()) (*)
- Misc style improvements (header layouts)
- Fixed (or blocked) some issues reported by linter
- Almost all classes have .cpp (instead of header-only) implementation now
- Headers use not #pragma once instead of #ifndef
- Disabled tests until MVP is ready
- Closes #10
- Closes #11 

Added 23 Nov:
- Compiling with clang works now (did not link)
- Minor changes in interface of DataArray, MemoryView
- Removed globals in favor of static owning methods (singleton pattern)
- Define TypeInfo global references of basic types
- More typedefs :)
- Fix detected bugs in DataArray

### CODE REVIEW

File: include/typedefs.hpp [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#pragma once
+
+#include <memory>
+#include <string>
+#include <unordered_map>
+#include <vector>
+
+using String = std::string;
```
Comment (adajed) [inline include/typedefs.hpp]: Is it necessary? It's not a mistake but `std::string` is not so long :P When I saw `String` in some code I wondered where it came from.

File: src/DataArray.cpp [hunk 2]
```diff
@@ -1,62 +1,126 @@
...
+	}
+
+	bool currentIsNewer = data[currentLocation].revision > data[targetLocation].revision;
+	// Target location must have >= space than current location.
+	// If current version is newer, do not preserve target location data.
+	ensureLocationCapacity(targetLocation, getLocationCapacity(currentLocation), !currentIsNewer);
+
+	if (currentIsNewer) {
+		resourceManager.copyMemory(
+		data[targetLocation].maybeMemory->getView(),
```
Comment (adajed) [inline src/DataArray.cpp]: tab? :)

File: src/DataArray.cpp [hunk 3]
```diff
@@ -1,62 +1,126 @@
...
+	MemoryView dstView = data[currentLocation].maybeMemory->getView().getSuffix(getCount() * typeInfo.getSize());
+	resourceManager.copyMemoryExternal(dstView, elements, count * typeInfo.getSize());
+	data[currentLocation].revision += 1;
+	elemCount += count;
+}
+
+void DataArray::appendDefault(std::size_t count)
+{
+	for (std::size_t i = 0; i < count; ++i) {
+		appendImpl(typeInfo.getRuntimeTypeInfo(), typeInfo.getDefaultValuePtr(), 1);
```
Comment (adajed) [inline src/DataArray.cpp]: this would increase revision by count. Is it what you had in mind?

File: src/MemoryView.cpp [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+MemoryView MemoryView::getSuffix(std::size_t bytesToSkip) const
+{
+	return MemoryView(owner, begin + bytesToSkip, end);
+}
+
+void* MemoryView::getPtr() const
+{
+	// NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
+	return const_cast<void*>(reinterpret_cast<const void*>(reinterpret_cast<const char*>(owner->ptr) + begin));
```
Comment (adajed) [inline src/MemoryView.cpp]: oh boy :D

File: src/TypeRegistry.cpp [hunk 5]
```diff
@@ -1,29 +1,55 @@
...
-	if (it == nameToTypeInfoPtr.end())
-		throw std::runtime_error(boost::str(boost::format("TypeRegistry: requested unknown type %1%") % name));
-	return it->second;
+	return *byType.at(std::type_index(typeId));
 }
+
+const TypeInfo& TypeRegistry::searchByName(const String& name) const
+{
+	try {
+		return *byName.at(name);
```
Comment (adajed) [inline src/TypeRegistry.cpp]: is there really no exception-free solution to checking whether element is in map?

File: include/typedefs.hpp (hunk 1 above)
Comment (prybicki) [reply include/typedefs.hpp]: It came from a world of sane naming convention when type starts with capital letter. This is actually a patch for STL.

File: src/DataArray.cpp (hunk 3 above)
Comment (prybicki) [reply src/DataArray.cpp]: Good catch, I didn't intent that. However, this behavior is completely harmless, because differences between revisions have no meaning. I'll probably fix it in some time, even to save increment op.

File: src/MemoryView.cpp (hunk 4 above)
Comment (prybicki) [reply src/MemoryView.cpp]: There should be also NOREVIEWNEXTLINE directive :)

File: src/TypeRegistry.cpp (hunk 5 above)
Comment (prybicki) [reply src/TypeRegistry.cpp]: There is - .find(). But then you have to check against its return (which can be either end() or iterator to found element). Which is better? Which is faster? I do not know, didn't measure.

Comment (adajed) [reply src/TypeRegistry.cpp]: Still this is not what exceptions are for ;) And there is also .count() that you can use.

File: src/DataArray.cpp (hunk 2 above)
Comment (adajed) [reply src/DataArray.cpp]: Why `resourceManager.copyMemory(` and `data[targetLocation].maybeMemory->getView(),` are at the same indentation level?

Comment (prybicki) [reply src/DataArray.cpp]: This is single call, so indent level is equal. Same apply for long exceptions. This was produced by clang-format.

File: src/TypeRegistry.cpp (hunk 5 above)
Comment (prybicki) [reply src/TypeRegistry.cpp]: Yup, I believe you're right and will change that.

Comment (prybicki) [reply src/TypeRegistry.cpp]: After re-thinking I disagree with you. This is what exceptions are for. Namely, they split otherwise mixed success and failure code path. Started to make them exception free and my feel was that I'm regressing to C-style error handling.
